### ISSUE TITLE
App crashes after latest update

### ISSUE THREAD

**Issue by smnthermes** [39aldo39/DecSyncCC#16]
`FATAL EXCEPTION: main
Process: org.decsync.cc, PID: 16492
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.decsync.cc/org.decsync.cc.MainActivity}: java.io.FileNotFoundException: /storage/emulated/10/DecSync/.decsync-info (No such file or directory)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.io.FileNotFoundException: /storage/emulated/10/DecSync/.decsync-info (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:308)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:84)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:110)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:110)
	at org.decsync.library.DecsyncKt.checkDecsyncInfo(Decsync.kt:560)
	at org.decsync.cc.MainActivity.onCreate(MainActivity.kt:60)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more`

**Comment by 39aldo39** [comment]
Thanks for the report!

I have committed a fix, which should resolve the issue.

As a workaround you can create the directory `/storage/emulated/10/DecSync`. The crash also only occurs when it is the first time DecSync, otherwise the directory already exists.
