### ISSUE TITLE
Crash when modifying a reccuring event

### ISSUE THREAD

**Issue by PaperMountainStudio** [39aldo39/DecSyncCC#27]
# steps to reproduce
1. setup a decsync calendar
2. create a recurring event
3. delete one occurence from the middle
4. synchronize with decsync

```
java.io.FileNotFoundException: Couldn't find event 10
	at at.bitfire.ical4android.AndroidEvent.getEvent(AndroidEvent.kt:151)
	at org.decsync.cc.calendars.LocalEvent.writeUpdateAction(LocalEvent.kt:54)
	at org.decsync.cc.calendars.CalendarsService$CalendarsSyncAdapter.onPerformSync(CalendarsService.kt:121)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)
```

**Comment by 39aldo39** [comment]
I cannot reproduce this crash, because I cannot delete one occurrence when the event is not yet synchronized in Etar. Maybe you can do so in other calendar applications, if so which one did you use? Note that I can do it with an extra sync between 2 and 3, but then there is no crash.

**Comment by PaperMountainStudio** [comment]
I tried triggering the error again, but I wasn't successful. This is
weird, because I was running into it all the time. The only thing that
changed is that I upgraded to Android 10. I think you can close it.
