### ISSUE TITLE
Crash on first launch and after confirming storage location

### ISSUE THREAD

**Issue by renyuneyun** [39aldo39/DecSyncCC#57]
I'm experiencing crash recently (it worked well previously). Therefore, I planned to reset the app.
After resetting, it crashes on the first screen (welcome), after launched for 0.5s. I granted the write permission, and this won't crash.
However, after choosing the storage location afterwards, and pressing the "next" button, it crashes again. It never shows the actual main page of the app.

I copied the crash log below:

```


time: 1615647319041
msg: java.lang.Exception: Read empty file: org.decsync.library.RealFileSys@4c941a5
stacktrace: java.lang.Exception: Read empty file: org.decsync.library.RealFileSys@4c941a5
	at org.decsync.library.NativeFile.read(NativeFile.kt:4)
	at org.decsync.library.DecsyncFile.readLines(DecsyncFile.kt:1)
	at org.decsync.library.DecsyncFile.readLines$default(DecsyncFile.kt:1)
	at org.decsync.library.DecsyncV1$Companion.getStaticInfo(DecsyncV1.kt:6)
	at org.decsync.library.Decsync$Companion.getStaticInfo(Decsync.kt:6)
	at org.decsync.cc.MainActivity.loadBooks(MainActivity.kt:6)
	at org.decsync.cc.MainActivity.access$loadBooks(MainActivity.kt:1)
	at org.decsync.cc.MainActivity$onResume$3.invokeSuspend(MainActivity.kt:2)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

**Comment by renyuneyun** [comment]
By the way, the calendar entries were still being updated while the UI of the app crashes. I confirmed this before resetting the app.

**Comment by bugsbunny88** [comment]
any resolution on this?
